### ISSUE TITLE
Stays in pending state.

### ISSUE THREAD

**Issue by hemanth** [sindresorhus/gh-got#12]
```sh
$ node -v
5.0.1
```
![screen shot 2015-12-04 at 1 03 19 am](https://cloud.githubusercontent.com/assets/18315/11571551/f85dca86-9a22-11e5-8fee-06a2d50462e1.png)

Am I missing something here?

**Comment by SamVerschueren** [comment]
Try using a valid token.

**Comment by hemanth** [comment]
Token is mandatory?

**Comment by SamVerschueren** [comment]
If you pass in a token, it has to be valid. So either you should remove the token or pass in a valid one. The reason why it does nothing is probably because you are not handling the errors.

**Comment by SamVerschueren** [comment]
@hemanth ping

**Comment by hemanth** [comment]
:+1:
