### ISSUE TITLE
Pass in entire GH url as path

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/gh-got#13]
The link header returns URLs for the next, previous, last and first pages. I think it would be nice to use them directly in a `gh-got` call without having to provide an empty endpoint option.

Just a little example:
```js
const linkParse = require('github-link-parse');

function fetch(user, opts, url) {
    return ghGot(url || `/users/${user}/repos`, {token: opts.token})
        .then(res => {
            const links = linkParse(res.headers.link);

            if(links.next) {
                return fetch(user, opts, links.next);
            }
        });
}
```

We can check if the path starts with `http(s)` and use that as the entire url instead of as path. Can do a PR if you want.

**Comment by sindresorhus** [comment]
:+1: Ensure to mention it in the docs.
