### ISSUE TITLE
Reversing priority of token and endpoint environment variables

### ISSUE THREAD

**Issue by millette** [sindresorhus/gh-got#16]
Started as a [line comment](https://github.com/sindresorhus/gh-got/commit/1fc6d0265d03a4cf0982464d458db7d7872d9d21#commitcomment-17035522) but let's make it an issue and fix/close it.

The readme says clearly:
> Can be overridden globally with the GITHUB_TOKEN environment variable.

Same for the endpoint.

Not sure what the logic was, but I think it would be preferable to use the environment variables only when no applicable argument is passed. An application could have a default token (the env.) but for whatever reason use another token on specific calls.

The module, readme and test would have to be updated. It could be considered a major change since it's reversing its meaning.

**Comment by sindresorhus** [comment]
Makes sense to me.

@floatdrop @SamVerschueren Thoughts?

**Comment by SamVerschueren** [comment]
Makes sense to me as well. The options object has higher priority then other global settings.

**Comment by floatdrop** [comment]
Yep, options should not be overridden by globals.

**Comment by sindresorhus** [comment]
Alright. Let's do it. PR welcome.
