### ISSUE TITLE
Populate error with information from Github

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/gh-got#19]
The Github API returns error information in the body as encoded json, it would be nice to get better error messages by using this information.

e.g.

``` http
HTTP/1.1 400 Bad Request
Content-Length: 35

{"message":"Problems parsing JSON"}
```

currently results in:

``` text
HTTPError: Response code 400 (Bad Request)
```

would be nice to get something like:

``` text
GithubError: Problems parsing JSON (400)
```

**Comment by sindresorhus** [comment]
Great idea! Interested in doing a pull request?

**Comment by sindresorhus** [comment]
Should also include the `errors` field:

```
HTTP/1.1 422 Unprocessable Entity
Content-Length: 149

{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Issue",
      "field": "title",
      "code": "missing_field"
    }
  ]
}
```

**Comment by satazor** [comment]
Is this really necessary? error.response.body contains the github response, https://github.com/sindresorhus/got/blob/master/index.js#L144

**Comment by sindresorhus** [comment]
@satazor It's just to improve the DX, so you can see right away what's wrong. My comment is probably moot though.

**Comment by kevva** [comment]
Do we want this in the streaming API too? That'd require some more work since we have to fetch the response stream to get the body. Also, I think we have to proxy the events because AFAIK we can't just listen on `error` and then emit `error` with the formatted one inside it.

**Comment by sindresorhus** [comment]
@kevva Nah. Too much work. We can just document that it doesn't work with the stream API.

**Comment by kevva** [comment]
@sindresorhus, haha, I asked because I've already done it, but I don't think it looks good 😸 .
