### ISSUE TITLE
silent or mute option?

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/gh-got#2]
this passing noop function to got is weird and okey I understand why is it, but break some things sometimes. I think better would be to have silent or mute option and pass it if you dont want to catch the things.

**Comment by floatdrop** [comment]
@tunnckoCore could you add links to code and/or examples?

**Comment by tunnckoCore** [comment]
Its specific. I use it with https://github.com/hybridables/hybridify.

upcoming refactor of github-generate-token
```js
var got = require('gh-got');
var kindOf = require('kind-of');
var hybridify = require('hybridify');
var get = hybridify(got);

module.exports = function githubGenerateToken(pattern, opts, callback) {
  if (kindOf(pattern) !== 'string') {
    throw new TypeError('[github-generate-token] expect `pattern` be string');
  }
  if (pattern.indexOf(':') === -1) {
    throw new Error('[github-generate-token] invalid `pattern` given');
  }
  if (!callback && kindOf(opts) === 'function') {
    callback = opts;
    opts = {};
  }

  var auth = '';
  var meta = pattern.split(':');

  auth = meta[0] + meta[1];
  opts = kindOf(opts) === 'object' ? opts : {};

  opts.scopes = kindOf(opts.scopes) === 'array';
  opts.note = kindOf(opts.note) === 'string';

  var body = {};
  body.scopes = opts.scopes ? opts.scopes : ['user', 'repo', 'gist'];
  body.note = opts.note ? opts.note : 'tunnckoCore/github-generate-token';

  return get('authorizations', {
    body: JSON.stringify(body),
    headers: {
      'authorization': 'Basic ' + new Buffer(auth).toString('base64')
    }
  }, callback);
};
```

the idea behind `hybridify` and hybrid modules like `then-got` and `exec-cmd` is to make the callback  optional. And if callback isn't passed the it will work as promise. So i want that in this module.

So if I go and test this module like
```js
genGithubToken('foobarbazqux:foobarbazqux')
.catch(function(e) {
  console.log('promise err:', err);
})
```
im not able to catch the error which would be 401 because the credentials is not okey. But here comes the problem. ghGot pass this weird noop callback to got and got think all is okey, i mean.. it pass the error to this noop function which I dont want, cuz im trying to catch it with `.catch` in this test. But yea, this works

```js
genGithubToken('foobarbazqux:foobarbazqux', function(err) {
  console.log('callback err:', err);
})
.catch(function(err) {
  console.log('promise err:', err);
})
```

**Comment by floatdrop** [comment]
thanks. I'm not familiar with hibridify, but shouldn't it always pass callback with resolve/reject logic to `gh-got` and return wrapped function with right logic (with/without callback)?

**Comment by tunnckoCore** [comment]
> but shouldn't it always pass callback with resolve/reject logic to gh-got and return wrapped function with right logic (with/without callback)?

that's the idea of hybridify. to allow users to use or not callbacks. Look at [hybridify#L58-L60](https://github.com/hybridables/hybridify/blob/master/index.js#L58-L60) where it uses [handle-callback](https://github.com/hybridables/handle-callback/blob/master/index.js#L28-L36), which is exactly what you suggests - wrappers on top of callbacks and promises.

**Comment by sindresorhus** [comment]
I still don't understand what you're asking of us. Maybe do a PR instead showing what changes you want?

**Comment by tunnckoCore** [comment]
hi,
asking for `silent` or `mute` option that if it is true will pass noop function to `got` as now [if not defined](https://github.com/sindresorhus/gh-got/blob/master/index.js#L15).
The problem is that `got` understands "if I dont have callback function user want stream behaving", but  in my case when dont have callback it should behave as promise - the case is "if github-generate-token dont have callback function user expects promise behving".

**Comment by sindresorhus** [comment]
Not going that add an option for this obscure use-case. We're planning to add promise support to `got` soon anyways.
