### ISSUE TITLE
Automatic retry when receiving 5xx responses

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/gh-got#25]
I am a heavy user of `gh-got` as part of [renovate](https://github.com/singapore/renovate). A small percentage of request receive a `502 Bad Gateway` response and it's pretty obvious that these should be retried *somewhere* in the stack rather than bailing and stopping all subsequent processing.

I was going to write a wrapper around `gh-got` to achieve this but then thought I'd open an issue here for discussion first as it seems like something all users of `gh-got` would benefit from and not specific to my application.

Relevant thread there: https://github.com/sindresorhus/got/issues/199 (kind of dismissing the idea).

Additionally: I do not need stream support

**Comment by sindresorhus** [comment]
Sure, that could be useful. Could probably use https://github.com/sindresorhus/p-retry for this.

**Comment by rarkins** [comment]
Thanks for the feedback and pointer to `p-retry`. What I plan to do is incorporate a `p-retry` wrapper within my application first and observe its results for a while before proposing the enhancement into `gh-got` here.
