### ISSUE TITLE
Streaming interface

### ISSUE THREAD

**Issue by kevva** [sindresorhus/gh-got#3]
Like `got`, this should have a streaming interface.

**Comment by kevva** [comment]
@sindresorhus, since `got@4.x.x` the streaming interface broke again :P.

**Comment by sindresorhus** [comment]
Didn't really break as it was never documented, but happy to add it officially.

**Comment by floatdrop** [comment]
@kevva they were always working ([we have tests for that](https://github.com/sindresorhus/got/blob/master/test/stream.js)), but API is changed in `4.0.0` (it was major release because of that).

@sindresorhus it was always written in usage, but may be it is not enough.

**Comment by kevva** [comment]
@floatdrop, yea, I know :P. I meant that it broke in `4.0.0` because of this module only returning `got`.
