### ISSUE TITLE
Add GraphQL Support

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/gh-got#39]
It would be useful if gh-got provided a `graphql` function that made requests using the [GitHub GraphQL API v4](https://docs.github.com/en/graphql).

// @sindresorhus

**Comment by sindresorhus** [comment]
Agreed

**Comment by fregante** [comment]
I just remembered about this wrapper. Why would one use it instead of the official ones?

https://github.com/octokit/rest.js
https://github.com/octokit/graphql.js

First party, well typed, paginated, etc

**Comment by sindresorhus** [comment]
@fregante The official clients came out (or rather [was officially adopted by GitHub](https://github.com/octokit/rest.js#credits)) two years after this package was made.

This package is mostly just useful if you want low overhead and just need a couple of API calls.

We should definitely add those packages to the readme as recommendations.

**Comment by fregante** [comment]
> two years after this package was made

I'm aware, but I'm very quick to deprecate my own packages when I see someone found a better solution. Specifically for this issue I don't think it's a good investment to add GraphQL here when there's already something.

> package is mostly just useful if you want low overhead

I think `got` has more overhead than you think 😅 

```
❯ npx package-size gh-got @octokit/rest

  package               size       minified   gzipped
  gh-got@9.0.0          755.86 KB  221.33 KB  68.36 KB
  @octokit/rest@18.0.6  128.98 KB  59.06 KB   12.67 KB
```

**Comment by sindresorhus** [comment]
You're right. No reason to use this package, unless you really want raw access to the endpoints for some reason. And no point in adding more features.
